# Generated by Django 5.2.1 on 2025-05-08 13:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('car_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('COUPE', 'Coupe'), ('WAGON', 'Wagon'), ('CABRIO', 'Cabrio'), ('SUV', 'SUV')], max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('engine_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('odometer', models.IntegerField()),
                ('year_of_production', models.IntegerField()),
                ('vin_number', models.CharField(max_length=17, unique=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('COUPE', 'Coupe'), ('WAGON', 'Wagon'), ('CABRIO', 'Cabrio'), ('SUV', 'SUV')], max_length=20, unique=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_start_date', models.DateField(default=django.utils.timezone.now)),
                ('rent_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rent_complete', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='car_rental.car', to_field='registration_number')),
            ],
        ),
    ]
